### ISSUE TITLE
gcc 4.8 build

### ISSUE THREAD

**Issue by Michel2904** [Iyengar111/NanoLog#17]
I'm trying to build NanoLog using gcc 4.8 on CentOS 7.3 64bit and it fails. I receive 2 errors:

NanoLog.cpp:357:86: error: size of array ‘padding’ is too large
      char padding[256 - sizeof(std::atomic_flag) - sizeof(char) - sizeof(NanoLogLine)];
                                                                                      ^
NanoLog.cpp: In constructor ‘nanolog::RingBuffer::RingBuffer(size_t)’:
NanoLog.cpp:371:6: error: static assertion failed: Unexpected size != 256
      static_assert(sizeof(Item) == 256, "Unexpected size != 256");

The sizeof(NanoLogLine) is 256 so that seems to be the issue. Do I need a newer gcc to build this?

**Comment by vivekvrao** [comment]
on linux with gcc - the NanoLogLine comes to 256 bytes - hence the size of padding [256 - sizeof(std::atomic_flag) - sizeof(char) - sizeof(NanoLogLine)] - comes to negative number. No idea what its for - and why thats the case.

**Comment by Iyengar111** [comment]
Hey guys,

Thanks for raising this. Its a bug that gets seen only on 64bit os. Previously i had 2 members in nanologline as unint32_t. I believe one the contributors changed it to size_t but forgot to change the type in the padding. On 32 bit size_t is the same as uint32_t so I never noticed this issue. 64 bit size_t is 2 times that of uint32_t so compilation fails.

Ill fix this soon.

Thanks for raising.

Karthik Iyengar

**Comment by Iyengar111** [comment]
Fixed now.

**Comment by Michel2904** [comment]
I can confirm this is fixed now! 

Thanks, 

Michel

**Comment by chengm349** [comment]
Hi Karthik Iyengar

the link's Usage shows to write to a file. How to write to stdout/stderr? If I want to log a thread ID for each log line, how to do it?

**Comment by chengm349** [comment]
Hi Karthik Iyengar,

Also seems nanolog is not actively maintained?
