### ISSUE TITLE
Remove full path from __FILE__ and only keep filename

### ISSUE THREAD

**Issue by cstamatopoulos** [Iyengar111/NanoLog#19]
I feel it would preferable and cleaner to remove the full path of a file from the log.
Depending on how deep you are, the path can take a lot of space and clutter the log.

Assuming that you have seen g3log, this is also done there.
```
   std::string splitFileName(const std::string& str) {
      size_t found;
      found = str.find_last_of("(/\\");
      return str.substr(found + 1);
   }
```

**Comment by Iyengar111** [comment]
In a big project, 2 source files can have the same name.. Keeping the full path will remove any ambiguity which file the log line refers to. I wont be changing this.

If you want, it should be trivial for you to checkout the source code and add the split file name logic for your personal usage.
