### ISSUE TITLE
benchmark

### ISSUE THREAD

**Issue by KjellKod** [Iyengar111/NanoLog#2]
Hi, 

Something I thought of. The higher number of percentile the worse the performance, right? (unless my skim reading was bad). 

I think it would be even clearer if you explained that in your benchmark result table. Also maybe adding the numbers from "0 - 50 percentile" in one percentile "bucket" to even more highlight the kick-ass Nanolog :)

**Comment by Iyengar111** [comment]
Hi Kjell,

Yes higher number means worse performance.

Sorry I don't quite understand the 0-50 percentile in one bucket comment... Do you mean the other end of the spectrum (fastest log line latency ?)

**Comment by KjellKod** [comment]
Yes, that's what I mean.   Since in your test you run a set amount of log entries it can be understood if you read the code ... however for the visitor who just takes a quick glance he/she might miss that. 

... Maybe it doesn't make it clearer to show 0-50 percentile but I think you have all to gain from clarifying the percentile numbers.

**Comment by Iyengar111** [comment]
Ok. I put in a line "lower number means better performance".

**Comment by KjellKod** [comment]
Thanks
