### ISSUE TITLE
VS 2015  - ATOMIC_FLAG_INIT, ...

### ISSUE THREAD

**Issue by StephanusVictor** [Iyengar111/NanoLog#8]
Hi, 
I am not sure if this is the place or method, but I would like to report some issues.

I am trying out this lib in Visual Studio 15 (v140) and had to make three modifications to get it to compile and run.
1. Initialisation of the atomic_flag.  (2x locations)
I changed "flag(ATOMIC_FLAG_INIT )" to "flag{ ATOMIC_FLAG_INIT }"
ATOMIC_FLAG_INIT	is defined as {0}  and flag(ATOMIC_FLAG_INIT )  tries to invoke the copy constructor for the flag.
2. Initialise m_current_read_buffer to nullptr in class QueueBuffer.
3. #include <ctime> in cpp for format_timestamp() to work.

regards
Stephanus

**Comment by Iyengar111** [comment]
Hi Stephanus 

Thanks for informing me about the 3 modifications required for visual studio.

If it's ok with you, could you raise a pull request with the modifications you made ? I will merge it.

Alternatively if that's not possible for you, let me know and I will fix the code myself. 

Thanks

Karthik

**Comment by Iyengar111** [comment]
I have merged your pull request. Can I close this issue now ?

**Comment by StephanusVictor** [comment]
Yes,  thanks

**Comment by BTNC** [comment]
I include nanolog source in my project, build my project with `cmake -G "NMake Makefiles"` so that cmake chooses compiler from my local VS2015 update3 and run nmake to build the project. However I have to `#include <ctime>` in NanoLog.cpp to get it compiled. @Iyengar111 , could you help to check in the header change? Thanks

**Comment by Iyengar111** [comment]
I have #included <ctime>.
